package hangman;

public class CountryNames {

	public static String[] getCountryNames() {
		
		return new String[]{"AFGHANISTAN","ALBANIA","ALGERIA","ANDORRA","ANGOLA","ANGUILLA",
				"ANTARCTICA","ARGENTINA","ARMENIA","ARUBA","AUSTRALIA","AUSTRIA","AZERBAIJAN","BAHAMAS","BAHRAIN",
				"BANGLADESH","BARBADOS","BELARUS","BELGIUM","BELIZE","BENIN","BERMUDA","BHUTAN","BOLIVIA","BOTSWANA",
				"BRAZIL","BULGARIA","BURUNDI","CAMBODIA","CAMEROON","CANADA","CHAD","CHILE","CHINA","COLOMBIA",
				"COMOROS","CONGO","CROATIA","CUBA","CYPRUS","DENMARK","DJIBOUTI","DOMINICA","ECUADOR","EGYPT","ERITREA","ESTONIA","ETHIOPIA",
				"FIJI","FINLAND","FRANCE","GABON","GAMBIA","GEORGIA","GERMANY","GHANA","GIBRALTAR","GREECE","GREENLAND","GRENADA","GUADELOUPE","GUAM",
				"GUATEMALA","GUERNSEY","GUINEA","GUYANA","HAITI","HONDURAS","HONG KONG","HUNGARY","ICELAND","INDIA","INDONESIA","IRAQ","IRELAND","ISRAEL",
				"ITALY","JAMAICA","JAPAN","JERSEY","JORDAN","KAZAKHSTAN","KENYA","KIRIBATI","KOREA, REPUBLIC OF","KUWAIT","KYRGYZSTAN","LATVIA","LEBANON",
				"LESOTHO","LIBERIA","LIECHTENSTEIN","LITHUANIA","LUXEMBOURG","MACAO","MADAGASCAR","MALAWI","MALAYSIA","MALDIVES","MALI","MALTA","MARTINIQUE",
				"MAURITANIA","MAURITIUS","MAYOTTE","MEXICO","MONACO","MONGOLIA","MONTENEGRO","MONTSERRAT","MOROCCO","MOZAMBIQUE","MYANMAR","NAMIBIA","NAURU",
				"NEPAL","NETHERLANDS","NICARAGUA","NIGER","NIGERIA","NIUE","NORWAY","OMAN","PAKISTAN","PALAU","PANAMA","PARAGUAY","PERU","PHILIPPINES","PITCAIRN",
				"POLAND","PORTUGAL","QATAR","REUNION","ROMANIA","RWANDA","SAMOA","SAN MARINO","SAO TOME AND PRINCIPE","SAUDI ARABIA","SENEGAL","SERBIA",
				"SEYCHELLES","SINGAPORE","SLOVAKIA","SLOVENIA","SOMALIA","SPAIN","SRILANKA","SUDAN","SURINAME","SWAZILAND","SWEDEN","SWITZERLAND","TAJIKISTAN","THAILAND",
				"TOGO","TOKELAU","TONGA","TRINIDAD AND TOBAGO","TUNISIA","TURKEY","TURKMENISTAN","TURKS AND CAICOS ISLANDS","TUVALU","UGANDA","UKRAINE",
				"URUGUAY","UZBEKISTAN","VANUATU","VENEZUELA","VIETNAM","YEMEN","ZAMBIA","ZIMBABWE"};
		}
}
	

